global:
  resolve_timeout: 5m

  smtp_smarthost: "smtp.company.local:587"
  smtp_from: "db-monitoring@company.local"
  smtp_auth_username: "db-monitoring@company.local"
  smtp_auth_password: "CHANGE_ME"
  smtp_require_tls: true

route:
  receiver: "dba-email"
  group_by: ["alertname", "instance", "db_type", "app", "tier", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - matchers:
        - severity="critical"
      receiver: "dba-critical-email"
      repeat_interval: 1h

    - matchers:
        - severity="warning"
      receiver: "dba-warning-email"
      repeat_interval: 4h

receivers:
  - name: "dba-email"
    email_configs:
      - to: "dba-team@company.local"
        send_resolved: true

  - name: "dba-critical-email"
    email_configs:
      - to: "dba-team@company.local"
        send_resolved: true
        headers:
          subject: "[CRITICAL] {{ .CommonLabels.alertname }} - {{ .CommonLabels.instance }}"

  - name: "dba-warning-email"
    email_configs:
      - to: "dba-team@company.local"
        send_resolved: true
        headers:
          subject: "[WARNING] {{ .CommonLabels.alertname }} - {{ .CommonLabels.instance }}"

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname", "instance", "db_type"]
