- targets:
    - "10.243.176.251:9399"
  labels:
    service: "mssql"
    environment: "development"
    site: "development"
    team: "dba"
    role: "database"
    db_type: "mssql"
    app: "reporting"
    tier: "uat"
    owner: "team-data"

- targets:
    - "10.243.176.252:9399"
  labels:
    service: "mssql"
    environment: "development"
    site: "development"
    team: "dba"
    role: "database"
    db_type: "mssql"
    app: "etl"
    tier: "sit"
    owner: "team-data"

