- targets:
    - "10.243.176.250:9100"
  labels:
    service: "node"
    environment: "development"
    site: "development"
    team: "dba"
    role: "infrastructure"
    db_type: "none"
    app: "shared-infra"
    tier: "shared"
    owner: "infra-team"
