groups:
  - name: oracle-dpa-alerts
    rules:
      - alert: OracleExporterDown
        expr: up{job="oracle_exporter"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Oracle exporter is down"
          description: "Oracle exporter target is not reachable."

      - alert: OracleBlockedSessionsDetected
        expr: oracle_sessions_blocked_value > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Oracle blocking session detected"
          description: "There are blocked sessions in Oracle database."

      - alert: OracleHighActiveSessions
        expr: oracle_sessions_active_value > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High active sessions"
          description: "Oracle active sessions are above threshold."

      - alert: OracleHighDBTime
        expr: oracle_db_time_per_sec_value > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High DB time"
          description: "Oracle DB time per second is high."
